### ISSUE TITLE
G1 - Terminology generation and management

### ISSUE THREAD

**Issue by gwemon** [i-adopt/requirements#1]
This thread aims at compiling a set of requirements shared by all use cases listed as belonging to G1 (see [use_case_groups](https://github.com/i-adopt/usecase_analysis/blob/master/use_case_groups.csv))

**Comment by gwemon** [comment]
Requirements for G1 will need to be in tune with FAIR semantics criteria (preliminary recommendations and best practice recommendations). See https://zenodo.org/record/3707985#.XsJ1bmhKjb0

**Comment by mabablue** [comment]
R1. Terminology name (e.g., NERC)
R2. Globally unique, persistent and resolvable Identifier for the terminology
R3. Globally unique, persistent and resolvable Identifier for the terminology metadata record
R4. Globally unique, persistent and resolvable Identifier for the individual terms/classes
R5. Globally unique, persistent and resolvable Identifier for the individual relationship properties
R6. Terminology should be published in a semantic repository or at least publicly available
R7. The terminology should be compliant with Semantic Web and Linked Data standards
R8. The terminology should provide mappings to other terminologies
R9. Provide a terminology access endpoint (api) 
R10. Collections/branches (name, url) within the terminology that will be harvested and including their relations (e.g., skos:broader, exactMatch)
R11. Available provenance information (e.g. creation and modified dates) at term-level
R12. Term status (e.g., accepted)

**Comment by gwemon** [comment]
I am closing the group issues to declutter a little - we can reopen them if/when we need them
